services:
  - type: web
    name: deadline-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Set this in Render dashboard
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Set this in Render dashboard
